.PHONY: update-openfga
update-openfga:
	@printf 'package openfga\n\n// Code generated by Makefile; DO NOT EDIT.\n\nvar authModel = `%s`\n' '$(shell npx @openfga/syntax-transformer transform --from=dsl --inputFile=./lxd.openfga | jq -c)' > ./model.go